import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          FIN-REP!
        </h1>

        <p className={styles.description}>
          📈 开源的行情报表快速生成工具
        </p>

        <div className={styles.grid}>
          <a href="/rep/new" className={styles.card}>
            <h2>报表生成 &rarr;</h2>
          </a>

          <a href="/rep/list" className={styles.card}>
            <h2>报表查看 &rarr;</h2>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://twitter.com/kfchliu"
          target="_blank"
          rel="noopener noreferrer"
        >
          twitter
        </a>
        <a
          href="https://weibo.com/u/5717297833"
          target="_blank"
          rel="noopener noreferrer"
        >
          weibo
        </a>
        <a
          href="https://github.com/kf-liu"
          target="_blank"
          rel="noopener noreferrer"
        >
          github
        </a>
      </footer>
    </div>
  )
}
